### ISSUE TITLE
Don Bot: Failed to create the invite link :(

### ISSUE THREAD

**Issue by runIT123** [wireapp/don-bot#4]
Hello,

i try to set up an new wire bot with don bot. The creation of the bot works without any problems but if I try to enable the bot I get: "Failed to create the invite link :(" the whole time.

**Comment by dkovacevic** [comment]
Thanks. 
Can you retry enabling your bot now? It should be able to generate the link.

**Comment by runIT123** [comment]
Yeah, great it works!! Thank you for your fast support
