### ISSUE TITLE
Are user passwords stored in plaintext in the database?

### ISSUE THREAD

**Issue by cruatta** [wireapp/don-bot#5]
I was looking over the code and it doesn't appear as if passwords are being hashed during RegisterCommand before being stored by don bot in the database.

**Comment by dkovacevic** [comment]
You are correct. Don would issue a random generated password for your provider's account (not to be mistaken with your user's account on Wire) when registering. That password is stored in plain. However, users can authenticate with `auth` command and supply email/password that is routed to the backend and is never stored.
Unfortunately Wire does not provide password change for Providers yet (coming soon - end of Feb) so this random password cannot be changed.
Meanwhile I am planning to add password to `register` command so users can choose their password when registering (as opposed to getting a random one). In this case Don would store only the cookie (7 days expiration) and prompt user to authenticated again once it expires.  

For now I suggest to use [myprovider.sh](https://github.com/wireapp/echo-bot/blob/master/myprovider.sh) shell command to register as Provider and then authenticate with Don using that email/password

**Comment by dkovacevic** [comment]
#6
