### ISSUE TITLE
Can't open conversation with don-bot

### ISSUE THREAD

**Issue by JamieH** [wireapp/don-bot#6]
When I click: https://app.wire.com/?bot_name=don&bot_provider=d39b462f-7e60-4d88-82e1-44d632f94901&bot_service=7a7e5417-0ea3-4608-a5ff-cb809b93f65a a conversation with don-bot does not appear, it just opens the Wire client?

**Comment by dkovacevic** [comment]
This should be fixed now. Thanks for reporting!

**Comment by JamieH** [comment]
This doesn't seem to be working still?

**Comment by marcoconti83** [comment]
Hi @JamieH ,

Thank you for taking part in the beta phase of integrations for Wire. After some initial experimentation with integrations, we decided to streamline this feature for teams. 

You can create a team with a free month trial or join an existing team to keep using integrations; the link will work if you use a team account. 

If setting up a team account is not an option for you, please get in touch with us and we'll be happy to look for a solution.
